config/routes.rb
Rails.application.routes.draw do

  get 'log_in' => 'sessions#new', :as => 'log_in'
  get 'log_out' => 'sessions#destroy', :as => 'log_out'
  get 'sign_up' => 'students#new', :as => 'sign_up'

 resources :surveys
  post 'scores/new', to:'scores#new_post', as:'new_score_post'
  get 'scores/new', to:'scores#index', as:'new_score_get'
  resources :scores

  resources :surveys

  match 'surveys/new', :to => 'surveys#create', 
                       :via => :post, 
                       :as => :post_surveys
					   
    post '/pdf', to:'surveys#generate_pdf', as: 'generate_pdf' 
	get '/pdf', to:'lectures#index', as:'generate_pdf_get'

  get '/lectures/surveys/:id', to:'surveys#index_specific', as:'specific_surveys'
  
  post '/lectures/surveys/:id', to:'surveys#index_specific_post'

  resources :students
  resources :sessions

  get '/lectures', to:'lectures#index', as:'all_lectures'
  patch '/lectures/:id', to:'lectures#update'
  put '/lectures/:id', to:'lectures#update'
  delete '/lectures/:id', to:'lectures#destroy', as:'delete_lecture'
  resource :lectures
  get '/lectures/:id', to:'lectures#show', as:'lecture'
  get '/lectures/edit/:id', to:'lectures#edit', as:'edit_lecture'

  get '/statistics', to:'lectures#statistics', as:'statistics'
  get '/statistics/:id', to:'surveys#statistics_surveys', as:'statistics_surveys'
  post '/statistics/:id', to:'surveys#statistics_surveys_post'
  get '/statistics/:lecture_id_p/0', to:'surveys#statistics_surveys_all', as:'statistics_surveys_all'
  post '/statistics/:lecture_id_p/0', to:'surveys#statistics_specific_post'
  get '/statistics/:lecture_id_p/:survey_id_p', to:'surveys#statistics_specific', as:'statistics_specific'
  post '/statistics/:lecture_id_p/:survey_id_p', to:'surveys#statistics_specific_post'

   root 'welcome#index'

  

end

app/models/lecture.rb
class Lecture < ActiveRecord::Base
	has_many :surveys, dependent: :destroy
	has_many :score_archives, dependent: :destroy
	has_one :survey_statistics_summary

	delegate :average_general_score, :average_tempo_score, :average_importance_score, to: :survey_statistics_summary

	validates :name, :year, presence: true
	validates :year, numericality: {only_integer: true, greater_than_or_equal_to: Time.now.year, less_than_or_equal_to: Time.now.year+10 }

	def surveys_children?
		surveys.any?
	end

	def score_archives_children?
		score_archives.any?
	end

	def average_general_score
		survey_statistics_summary.general_score
	end
	def average_tempo_score
		survey_statistics_summary.tempo_score
	end
	def average_importance_score
		survey_statistics_summary.importance_score
	end
	def number_of_votes
		survey_statistics_summary.number_of_votes
	end

	def start_date_end_date_same_day
      if start_date.to_date != end_date.to_date
        errors.add(:base, 'Ankieta musi się rozpoczynać i kończyć w tym samym dniu!')
      end
 	end

end

app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
	
	layout :define_layout

	def index
		@all_lectures = Lecture.all
	end


	def statistics
		@all_lectures = Lecture.all
	end

	
	def new
		@lecture = Lecture.new
	end
	
	def edit
		@lecture = Lecture.find(params[:id])
	end
	
	def update
		@lecture = Lecture.find(params[:id])
		if @lecture.update(lecture_params)
			redirect_to all_lectures_path
		else
			render 'edit'
		end
	end
	
	def create
		@lecture = Lecture.new(lecture_params)
		if @lecture.save
			redirect_to all_lectures_path
		else
			render 'new'
		end
	end
	
	def show
		@lecture = Lecture.find(params[:id])
	end
	
	def destroy
		@lecture = Lecture.find(params[:id])
		@lecture.destroy
		
		redirect_to all_lectures_path
	end
	
	private
	def lecture_params
		params.require(:lecture).permit(:name,:year,:semester)
	end

	def define_layout
    # Check if logged in, because current_user could be nil.
      #if logged_in? and current_user.is_able_to('siteadmin')
        #{}"admin"
      #else
        #{}"application"
      #end
      "user"
    end
	
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/views/lectures/edit.html.erb
<% content_for :title do %>
  Edycja przedmiotu
<% end %>

<%= form_for :lecture, url: lecture_path(@lecture), method: :patch do |f| %>

<% if @lecture.errors.any? %>
    <div id="error_explanation">
      <h2>Wystąpiła następująca liczba błędów: <%=@lecture.errors.count%></h2>

      <ul>
      <% @lecture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
<% end %>

<div class=form>

<div class="field">
  <%= f.label :"Nazwa przedmiotu: " %>
  <%= f.text_field :name %>
</div>

<div class="field number">
  <%= f.label :"Rok: " %>
  <div><%= f.text_field :year, value:Time.now.year  %>
  <span class="minus"></span><span class="plus"></span></div>
</div>
<div></div>
<div class="field">
  <%= f.label:"Semestr: " %>
  <div>
  <div class="selector">
  <div class="styled_select">
  <%= f.select :semester, [['Zimowy','Z'],['Letni','L']] %>
  </div>
  </div>
  </div>
  <span id="width_tmp"></span>
</div>
  <% content_for :links do %>
    <div class="actions">
      <%= f.submit 'Dodaj', :class => 'button right' %>
    </div>
  <% end %>

</div>
<% end %>

<% content_for :links do %>
  <%= link_to 'Powrót', lectures_path, { :class=>"button right" } %>
<% end %>

app/views/lectures/index.html.erb
<% content_for :title do %>
  Lista przedmiotow
<% end %>
 
<table>
  <tr>
    <th>Przedmiot</th>
    <th>Rok</th>
	  <th>Semestr</th>

  </tr>
 
  <% @all_lectures.each do |lecture| %>
    <tr>
      <td><%= lecture.name %></td>
      <td><%= lecture.year %></td>
	    <td><%=
          if lecture.semester =='Z'
            'Zimowy'
          else
            'Letni'
          end
      %></td>
      <td class="link"><%=
          if lecture.score_archives_children? == false
            link_to 'Ankiety', specific_surveys_path(:id => lecture.id), { :class=>"goto" }
          end 
      %></td>
	    <td class="link"><%=
          if lecture.surveys_children? == false and lecture.score_archives_children? == false
            link_to 'Edytuj', edit_lecture_path(lecture), { :class=>"goto" }
          end 
      %></td>
	    <td class="link"><%= 
          if lecture.surveys_children? == false and lecture.score_archives_children? == false
            link_to 'Usuń', delete_lecture_path(lecture),
              method: :delete,
              data: { confirm: 'Czy na pewno chcesz usunac ten przedmiot?' },
              class: "delete" 
          end 
      %></td>          
    </tr>
  <% end %>
</table>

<% content_for :links do %>
  <%= link_to 'Dodaj nowy przedmiot', new_lectures_path, { :class=>"button right" } %>
<% end %>

app/views/lectures/new.html.erb
<% content_for :title do %>
  Nowy przedmiot
<% end %>

<%= form_for :lecture, url: lectures_path do |f| %>

<% if @lecture.errors.any? %>
    <div id="error_explanation">
      <h2>Wystąpiła następująca liczba błędów: <%=@lecture.errors.count%></h2>

      <ul>
      <% @lecture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
<% end %>

<div class=form>

<div class="field">
	<%= f.label :"Nazwa przedmiotu: " %>
	<%= f.text_field :name %>
</div>

<div class="field number">
	<%= f.label :"Rok: " %>
	<div><%= f.text_field :year, value:Time.now.year  %>
  <span class="minus"></span><span class="plus"></span></div>
</div>
<div class="field">
	<%= f.label:"Semestr: " %>
  <div>
  <div class="selector">
  <div class="styled_select">
	<%= f.select :semester, [['Zimowy','Z'],['Letni','L']] %>
  </div>
  </div>
  </div>
  <span id="width_tmp"></span>
</div>
    <div class="actions hidden">
      <%= f.submit 'Dodaj', :id => 'sumbit_form', :class => 'hidden' %>
    </div>
</div>
  
<% end %>


<% content_for :links do %>
  <label for="sumbit_form" class="button right">Dodaj</label>
  <%= link_to 'Powrót', lectures_path, { :class=>"button right" } %>
<% end %>

app/views/lectures/show.html.erb
 <%= link_to 'Powrot do listy przedmiotow', controller: 'lectures' %><br>
 <%= link_to 'Dodaj nowy przedmiot', new_lectures_path %><br>

<p>
  <strong>Nazwa:</strong>
  <%= @lecture.name %>
</p>
 
<p>
  <strong>Rok:</strong>
  <%= @lecture.year %>
</p>

<p>
  <strong>Semestr:</strong>
  <%= @lecture.semester %>
</p>

<%= link_to 'Edytuj', edit_lecture_path(@lecture) %>

app/views/lectures/statistics.html.erb
<% content_for :title do %>
Statystyki
<% end %>
 
<table>
  <tr>
    <th>Przedmiot</th>
    <th>Rok</th>
	  <th>Semestr</th>
    <th>Wrażenie ogólne</th>
    <th>Tempo</th>
    <th>Pożyteczność wiedzy</th>
    <th>Głosów</th>

  </tr>
 
  <% @all_lectures.each do |lecture| %>
    <tr>
      <td><%= lecture.name %></td>
      <td><%= lecture.year %></td>
	    <td><%=
          if lecture.semester =='Z'
            'Zimowy'
          else
            'Letni'
          end
      %></td>
      <td><%= lecture.average_general_score %></td>
      <td><%= lecture.average_tempo_score %></td>
      <td><%= lecture.average_importance_score %></td>
      <td><%= lecture.number_of_votes %></td>

      <td class="link"><%=
          if lecture.surveys_children? and lecture.number_of_votes > 0
            link_to '=>', statistics_surveys_path(:id => lecture.id), { :class => "goto"}
          end 
      %></td>         
    </tr>
  <% end %>
</table>