config/routes.rb
Rails.application.routes.draw do

  get 'log_in' => 'sessions#new', :as => 'log_in'
  get 'log_out' => 'sessions#destroy', :as => 'log_out'
  get 'sign_up' => 'students#new', :as => 'sign_up'

 resources :surveys
  post 'scores/new', to:'scores#new_post', as:'new_score_post'
  get 'scores/new', to:'scores#index', as:'new_score_get'
  resources :scores

  resources :surveys

  match 'surveys/new', :to => 'surveys#create', 
                       :via => :post, 
                       :as => :post_surveys
					   
    post '/pdf', to:'surveys#generate_pdf', as: 'generate_pdf' 
	get '/pdf', to:'lectures#index', as:'generate_pdf_get'

  get '/lectures/surveys/:id', to:'surveys#index_specific', as:'specific_surveys'
  
  post '/lectures/surveys/:id', to:'surveys#index_specific_post'

  resources :students
  resources :sessions

  get '/lectures', to:'lectures#index', as:'all_lectures'
  patch '/lectures/:id', to:'lectures#update'
  put '/lectures/:id', to:'lectures#update'
  delete '/lectures/:id', to:'lectures#destroy', as:'delete_lecture'
  resource :lectures
  get '/lectures/:id', to:'lectures#show', as:'lecture'
  get '/lectures/edit/:id', to:'lectures#edit', as:'edit_lecture'

  get '/statistics', to:'lectures#statistics', as:'statistics'
  get '/statistics/:id', to:'surveys#statistics_surveys', as:'statistics_surveys'
  post '/statistics/:id', to:'surveys#statistics_surveys_post'
  get '/statistics/:lecture_id_p/0', to:'surveys#statistics_surveys_all', as:'statistics_surveys_all'
  post '/statistics/:lecture_id_p/0', to:'surveys#statistics_specific_post'
  get '/statistics/:lecture_id_p/:survey_id_p', to:'surveys#statistics_specific', as:'statistics_specific'
  post '/statistics/:lecture_id_p/:survey_id_p', to:'surveys#statistics_specific_post'

   root 'welcome#index'

  

end

app/models/score.rb
class Score < ActiveRecord::Base
	belongs_to :survey
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :set_score, only: [:show, :update, :destroy]
 
  # GET /scores
  # GET /scores.json
  def index
    @scores = Score.all
	@surveys = Survey.all
	render :layout => false
  end
  


  # GET /scores/new
  def new
    @score = Score.new
  end

    # POST /scores/new
  def new_post
	
  	if  Survey.exists?(token: params[:survey][:token]) == true
  		params[:temp_s] = Survey.find_by(token: params[:survey][:token])
  		if Time.now >= params[:temp_s].start_date and Time.now <= params[:temp_s].end_date
  			@survey_id = params[:temp_s].id
  			@score = Score.new
  			params[:temp_l]= Lecture.find(params[:temp_s].lecture_id)
  			@lecture_name = params[:temp_l].name + " " + params[:temp_l].year.to_s
  			render :layout => false
  		else		
  			redirect_to scores_path(:me => 'Nie znaleziono ankiety!')
  		end
  	else
  		
  		redirect_to scores_path(:me => 'Nie znaleziono ankiety!')
  	end
  end



  # POST /scores
  # POST /scores.json
  def create
    @score = Score.new(score_params)
    respond_to do |format|
      if @score.save
	    
        format.html { redirect_to scores_path(:ms => 'Dziękujemy za ocenę!') }
        format.json { render :show, status: :created, location: @score }
      else
        format.html { render :new }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scores/1
  # DELETE /scores/1.json
  def destroy
    @score.destroy
    respond_to do |format|
      format.html { redirect_to scores_path, notice: 'Score was successfully destroyed.' }
      format.json { render :index, status: :destroyed, location: @score }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
	
    def set_score
      @score = Score.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def score_params
      params.require(:score).permit(:survey_id, :general_score, :tempo_score, :importance_score, :comment)
    end
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/scores/_form.html.erb
<%= form_for(@score) do |f| %>
  <% if @score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@score.errors.count, "error") %> prohibited this score from being saved:</h2>

      <ul>
      <% @score.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :survey_id %><br>
    <%= f.number_field :survey_id %>
  </div>
  <div class="field">
    <%= f.label :general_score %><br>
    <%= f.number_field :general_score %>
  </div>
  <div class="field">
    <%= f.label :tempo_score %><br>
    <%= f.number_field :tempo_score %>
  </div>
  <div class="field">
    <%= f.label :importance_score %><br>
    <%= f.number_field :importance_score %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_field :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scores/index.html.erb
<!DOCTYPE html>

<head>
  <title>eAnkieta</title>
  <meta name="viewport" content="width=device-width" />


  <style type="text/css">
  
			.score 
			{
				width: 500px;
			}
			h1
			{
				 margin-top: 10%;
				 margin-bottom: 10%;
			}
			form 
			{

				text-align: left;
			  
			}
			input[type=text],input[type=url], input[type=email], input[type=password], input[type=tel], textarea, text_field, select {

			  display: block;
			  margin-right: 0;
			  width: 100%; height: 40px;
			  line-height: 40px; 
			  font-size: 17px;
			  border: 1px solid #bbb;
			}


			[type=submit] {
				 -webkit-appearance: none; -moz-appearance: none;
				 display: block;
				 margin: 1.5em 0;
				 font-size: 1em; line-height: 2.5em;
				 color: #333;
				 font-weight: bold;
				 height: 2.5em; width: 100%;
				 background: #fdfdfd; background: -moz-linear-gradient(top, #fdfdfd 0%, #bebebe 100%); background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#fdfdfd), color-stop(100%,#bebebe)); background: -webkit-linear-gradient(top, #fdfdfd 0%,#bebebe 100%); background: -o-linear-gradient(top, #fdfdfd 0%,#bebebe 100%); background: -ms-linear-gradient(top, #fdfdfd 0%,#bebebe 100%); background: linear-gradient(to bottom, #fdfdfd 0%,#bebebe 100%);
				 border: 1px solid #bbb;
				 -webkit-border-radius: 10px; -moz-border-radius: 10px; border-radius: 10px;
			}



  
  			 @media only screen and (max-width: 600px){
            .score {
				width: 90%;
				font-size: 10px;
            }
			h1
			{
			 margin-top: 10%;
			 margin-bottom: 10%;
			}
			label{
				font-size: 17px;
			}
			form 
			{

				text-align: left;
			  
			}
			input[type=text],input[type=url], input[type=email], input[type=password], input[type=tel], textarea, text_field, select {

			  display: block;
			  margin-right: 0;
			  width: 100%; height: 40px;
			  line-height: 40px; 
			  font-size: 17px;
			  border: 1px solid #bbb;
			}


			[type=submit] {
				 -webkit-appearance: none; -moz-appearance: none;
				 display: block;
				 margin: 1.5em 0;
				 font-size: 15px; 
				 line-height: 2.5em;
				 color: #333;
				 font-weight: bold;
				 height: 50px; width: 100%;
				 background: #fdfdfd; background: -moz-linear-gradient(top, #fdfdfd 0%, #bebebe 100%); background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#fdfdfd), color-stop(100%,#bebebe)); background: -webkit-linear-gradient(top, #fdfdfd 0%,#bebebe 100%); background: -o-linear-gradient(top, #fdfdfd 0%,#bebebe 100%); background: -ms-linear-gradient(top, #fdfdfd 0%,#bebebe 100%); background: linear-gradient(to bottom, #fdfdfd 0%,#bebebe 100%);
				 border: 1px solid #bbb;
				 -webkit-border-radius: 10px; -moz-border-radius: 10px; border-radius: 10px;
			}
			}
			
			
			@media only screen and (max-width: 600px) and (orientation: landscape){
            .score {
				width: 90%;
				font-size: 6px;
            }
			h1
			{
			 margin-top: 5%;
			 margin-bottom: 0;
			}
			label{
				font-size: 10px;
			}
			form 
			{
				label font-size: 6px;
				font-size: 6px;
				text-align: left;

			  
			  }
			input[type=text], input[type=url], input[type=email], input[type=password], input[type=tel], textarea, text_field, select {

			  display: block;
			  margin-right: 0;
			  width: 100%; height: 20px;
			  line-height: 8px; font-size: 6px;
			  border: 1px solid #bbb;

			}


			[type=submit] {
			 -webkit-appearance: none; -moz-appearance: none;
			 display: block;
			 margin: 0.5em 0;
			 font-size: 10px; line-height: 15px;
			 color: #333;
			 font-weight: bold;
			 height: 25px; width: 100%;
			 background: #fdfdfd; background: -moz-linear-gradient(top, #fdfdfd 0%, #bebebe 100%); background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#fdfdfd), color-stop(100%,#bebebe)); background: -webkit-linear-gradient(top, #fdfdfd 0%,#bebebe 100%); background: -o-linear-gradient(top, #fdfdfd 0%,#bebebe 100%); background: -ms-linear-gradient(top, #fdfdfd 0%,#bebebe 100%); background: linear-gradient(to bottom, #fdfdfd 0%,#bebebe 100%);
			 border: 1px solid #bbb;
			 -webkit-border-radius: 10px; -moz-border-radius: 10px; border-radius: 10px;
			}
			}
			
			

   </style>

  
  <%= csrf_meta_tags %>
</head>

<body>
<center>
<div class="score"> 

<h1>Wprowadź token przedmiotu</h1>

<p style="color:red"><%= params[:me] %></p>
<p style="color:green"><%= params[:ms] %></p>


<%= form_for :survey, :url => new_score_post_path do |f| %>

    <p style="margin-right: 10px;">
    <%= f.label :TOKEN %><br>
    <%= f.text_field :token %>
  </p>
  
  <p>
    <%= f.submit :"Przejdź do ankiety" %>
  </p>
<% end %>

</form>

</div>
</center>
</body>

app/views/scores/new.html.erb
<div class="score">



<h1>New Score</h1>


<%= form_for :score, url: scores_path do |f| %>

    <p>
    <%= f.label :ID_Ankiety %><br>
    <%= f.text_field :survey_id , :value => @temp %>
  </p>
  
  
  

  <p>
    <%= f.label :Ocena_ogólna %><br>
    <%= f.select :general_score, [['bardzo dobrze', 5], ['dobrze', 4], ['średnio',3], ['słabo', 2], ['bardzo słabo', 1]] %>
  </p>
  
  <p>
    <%= f.label :Ocena_tempa %><br>
    <%= f.select :tempo_score, [['bardzo szybko', 5], ['szybko', 4], ['idealnie',3], ['wolno', 2], ['bardzo wolno', 1]] %>
  </p>

      <p>
    <%= f.label :Wartość_wiedzy %><br>
    <%= f.select :importance_score, [['bardzo dobrze', 5], ['dobrze', 4], ['średnio',3], ['słabo', 2], ['bardzo słabo', 1]] %>
  </p>
  
    <p>
    <%= f.label :Komentarz %><br>
    <%= f.text_area :comment , :maxlength => 200, :size => "30x6"%>
  </p>
  

 
  <p>
    <%= f.submit :Oceń%>
  </p>
<% end %>

<%= link_to 'Back', scores_path %>
</div>

app/views/scores/new_post.html.erb
<!DOCTYPE html>

<head>
  <title>eAnkieta</title>
  <meta name="viewport" content="width=device-width" />
    <style type="text/css">
  
			.score 
			{
				width: 500px;
			}
			h1
			{
				 margin-top: 10%;
				 margin-bottom: 10%;
			}
			form 
			{

				text-align: left;
			  
			}
			input[type=text],input[type=url], input[type=email], input[type=password], input[type=tel], textarea, text_field, select {

			  display: block;
			  margin-right: 0;
			  width: 100%; height: 40px;
			  line-height: 40px; 
			  font-size: 17px;
			  border: 1px solid #bbb;
			}


			[type=submit] {
				 -webkit-appearance: none; -moz-appearance: none;
				 display: block;
				 margin: 1.5em 0;
				 font-size: 1em; line-height: 2.5em;
				 color: #333;
				 font-weight: bold;
				 height: 2.5em; width: 100%;
				 background: #fdfdfd; background: -moz-linear-gradient(top, #fdfdfd 0%, #bebebe 100%); background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#fdfdfd), color-stop(100%,#bebebe)); background: -webkit-linear-gradient(top, #fdfdfd 0%,#bebebe 100%); background: -o-linear-gradient(top, #fdfdfd 0%,#bebebe 100%); background: -ms-linear-gradient(top, #fdfdfd 0%,#bebebe 100%); background: linear-gradient(to bottom, #fdfdfd 0%,#bebebe 100%);
				 border: 1px solid #bbb;
				 -webkit-border-radius: 10px; -moz-border-radius: 10px; border-radius: 10px;
			}



  
  			 @media only screen and (max-width: 600px){
            .score {
				width: 90%;
				font-size: 10px;
            }
			h1
			{
			 margin-top: 10%;
			 margin-bottom: 10%;
			}
			label{
				font-size: 17px;
			}
			form 
			{

				text-align: left;
			  
			}
			input[type=text],input[type=url], input[type=email], input[type=password], input[type=tel], textarea, text_field, select {

			  display: block;
			  margin-right: 0;
			  width: 100%; height: 40px;
			  line-height: 40px; 
			  font-size: 17px;
			  border: 1px solid #bbb;
			}


			[type=submit] {
				 -webkit-appearance: none; -moz-appearance: none;
				 display: block;
				 margin: 1.5em 0;
				 font-size: 15px; 
				 line-height: 2.5em;
				 color: #333;
				 font-weight: bold;
				 height: 50px; width: 100%;
				 background: #fdfdfd; background: -moz-linear-gradient(top, #fdfdfd 0%, #bebebe 100%); background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#fdfdfd), color-stop(100%,#bebebe)); background: -webkit-linear-gradient(top, #fdfdfd 0%,#bebebe 100%); background: -o-linear-gradient(top, #fdfdfd 0%,#bebebe 100%); background: -ms-linear-gradient(top, #fdfdfd 0%,#bebebe 100%); background: linear-gradient(to bottom, #fdfdfd 0%,#bebebe 100%);
				 border: 1px solid #bbb;
				 -webkit-border-radius: 10px; -moz-border-radius: 10px; border-radius: 10px;
			}
			}
			
			
			@media only screen and (max-width: 600px) and (orientation: landscape){
            .score {
				width: 90%;
				font-size: 6px;
            }
			h1
			{
			 margin-top: 5%;
			 margin-bottom: 0;
			}
			label{
				font-size: 10px;
			}
			form 
			{
				label font-size: 6px;
				font-size: 6px;
				text-align: left;

			  
			  }
			input[type=text], input[type=url], input[type=email], input[type=password], input[type=tel], textarea, text_field, select {

			  display: block;
			  margin-right: 0;
			  width: 100%; height: 20px;
			  line-height: 8px; font-size: 6px;
			  border: 1px solid #bbb;

			}


			[type=submit] {
			 -webkit-appearance: none; -moz-appearance: none;
			 display: block;
			 margin: 0.5em 0;
			 font-size: 10px; line-height: 15px;
			 color: #333;
			 font-weight: bold;
			 height: 25px; width: 100%;
			 background: #fdfdfd; background: -moz-linear-gradient(top, #fdfdfd 0%, #bebebe 100%); background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#fdfdfd), color-stop(100%,#bebebe)); background: -webkit-linear-gradient(top, #fdfdfd 0%,#bebebe 100%); background: -o-linear-gradient(top, #fdfdfd 0%,#bebebe 100%); background: -ms-linear-gradient(top, #fdfdfd 0%,#bebebe 100%); background: linear-gradient(to bottom, #fdfdfd 0%,#bebebe 100%);
			 border: 1px solid #bbb;
			 -webkit-border-radius: 10px; -moz-border-radius: 10px; border-radius: 10px;
			}
			}
			
			

   </style>

   
  <%= csrf_meta_tags %>
  

</head>
<center>
<div class="score">


<h1><%= @lecture_name %></h1>

<%= form_for :score, url: scores_path do |f| %>
    
    <%= f.hidden_field :survey_id , :value => @survey_id %>

  <p>
    <%= f.label :Ocena_ogólna %><br>
    <%= f.select :general_score, [['bardzo dobrze', 5], ['dobrze', 4], ['średnio',3], ['słabo', 2], ['bardzo słabo', 1]] %>
  </p>
  
  <p>
    <%= f.label :Ocena_tempa %><br>
    <%= f.select :tempo_score, [['bardzo szybko', 5], ['szybko', 4], ['idealnie',3], ['wolno', 2], ['bardzo wolno', 1]] %>
  </p>

      <p>
    <%= f.label :Wartość_wiedzy %><br>
    <%= f.select :importance_score, [['bardzo dobrze', 5], ['dobrze', 4], ['średnio',3], ['słabo', 2], ['bardzo słabo', 1]] %>
  </p>
  
    <p>
    <%= f.label :Komentarz %><br>
    <%= f.text_area :comment %>
  </p>
  

 
  <p>
    <%= f.submit :Oceń%>
  </p>
<% end %>
<br>
<%= button_to 'Powrót', scores_path, :method => :get %>
</div>
</center>