config/routes.rb
Rails.application.routes.draw do

  get 'log_in' => 'sessions#new', :as => 'log_in'
  get 'log_out' => 'sessions#destroy', :as => 'log_out'
  get 'sign_up' => 'students#new', :as => 'sign_up'

 resources :surveys
  post 'scores/new', to:'scores#new_post', as:'new_score_post'
  get 'scores/new', to:'scores#index', as:'new_score_get'
  resources :scores

  resources :surveys

  match 'surveys/new', :to => 'surveys#create', 
                       :via => :post, 
                       :as => :post_surveys
					   
    post '/pdf', to:'surveys#generate_pdf', as: 'generate_pdf' 
	get '/pdf', to:'lectures#index', as:'generate_pdf_get'

  get '/lectures/surveys/:id', to:'surveys#index_specific', as:'specific_surveys'
  
  post '/lectures/surveys/:id', to:'surveys#index_specific_post'

  resources :students
  resources :sessions

  get '/lectures', to:'lectures#index', as:'all_lectures'
  patch '/lectures/:id', to:'lectures#update'
  put '/lectures/:id', to:'lectures#update'
  delete '/lectures/:id', to:'lectures#destroy', as:'delete_lecture'
  resource :lectures
  get '/lectures/:id', to:'lectures#show', as:'lecture'
  get '/lectures/edit/:id', to:'lectures#edit', as:'edit_lecture'

  get '/statistics', to:'lectures#statistics', as:'statistics'
  get '/statistics/:id', to:'surveys#statistics_surveys', as:'statistics_surveys'
  post '/statistics/:id', to:'surveys#statistics_surveys_post'
  get '/statistics/:lecture_id_p/0', to:'surveys#statistics_surveys_all', as:'statistics_surveys_all'
  post '/statistics/:lecture_id_p/0', to:'surveys#statistics_specific_post'
  get '/statistics/:lecture_id_p/:survey_id_p', to:'surveys#statistics_specific', as:'statistics_specific'
  post '/statistics/:lecture_id_p/:survey_id_p', to:'surveys#statistics_specific_post'

   root 'welcome#index'

  

end

app/models/survey.rb
class Survey < ActiveRecord::Base
	has_many :scores
	belongs_to :lecture
	attr_accessor :interval
	attr_accessor :number_of_surveys

	validates :start_date, :end_date, presence: true

	validates :interval, presence: true, :on => :create
	validates :number_of_surveys, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 20 }, :on => :create
	validate  :start_date_before_end_date,:start_date_end_date_same_day, :dates_later_than_current, :is_valid_datetime
  	
  	def average_general_score
  		scores.average(:general_score)
  	end
  	def average_tempo_score
  		scores.average(:tempo_score)
  	end
  	def average_importance_score
  		scores.average(:importance_score)
  	end
  	def number_of_comments
  		#scores.where("COALESCE(comment,'') = ?", '').count
  		scores.where("comment != ?",'').count
  	end
  	def number_of_votes
  		scores.count
  	end

	def children?
    	scores.any?
  	end

  def start_date_before_end_date
    	if end_date <= start_date
     		errors.add(:base, 'Godzina rozpoczęcia ankiety musi być wcześniejsza niż jej zakończenia!')
    	end
 	end

  def start_date_end_date_same_day
      if start_date.to_date != end_date.to_date
        errors.add(:base, 'Ankieta musi się rozpoczynać i kończyć w tym samym dniu!')
      end
  end

 	def dates_later_than_current
 		if start_date < Time.now
 			errors.add(:base, 'Nie można tworzyć ankiet w przeszłości!')
 		end
 	end

 	def is_valid_datetime
    	errors.add(:base ,'Data nie istnieje!') if (Date.valid_date?(start_date.year,start_date.month,start_date.mday) == false)
  end



end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: [:show, :edit, :update, :destroy]
  layout :define_layout

  # GET /lectures/surveys/1
  # GET /lectures/surveys/1.json
  def index_specific
      #show all surveys for select lecture: edit, delete, print...
      lectures_for_selector_s = Array.new
      lectures_temp = Lecture.all.order(updated_at: :desc)
      lectures_temp.each do |lecture|
        if lecture.score_archives_children? == false
          lectures_for_selector_s.push([lecture.name, lecture.id])
        end
      end
      flash[:lectures_for_selector_s] = lectures_for_selector_s

    lecture = Lecture.find(params[:id])
    @surveys = lecture.surveys.order(start_date: :desc)
    flash[:lecture_id_flash]= params[:id]
	
	#respond_to do |format|
	#	format.html
	#	format.pdf do
	#		
	#		pdf = PDF::Writer.new
	#		pdf.text 'Hello world!'
	#		send_data pdf.render, :filename => "1.pdf", :type => "application/pdf", :disposition => "inline"
	#	end
	#end

  end

  def generate_pdf
	html = ""
	lecture = Lecture.find(params[:lecture][:id])
	html = html + "<head>
	<title>" + lecture.name + "</title>
	<style>
		table {
			clear: both;
			border-collapse: collapse;
			text-align: center;
		}

		table th{
			padding:5px;
			padding-left:20px;
			padding-right:20px;
			border: outset 2px;
			background-color: #D6DEE1;
			color: #003366;
		}

		table td{
			padding:5px;
			padding-left:20px;
			padding-right:20px;
			border: outset 2px;
		}
	</style>
	</head><p style='font-size: 32px'><strong>"+lecture.name+"</strong></p><br><table style='font-size: 20px'>    
	<thead>  
      <tr>      
        <th rowspan='2'>Data zajęć</th>
        <th colspan='2'>Ważność tokenu</th>
        <th rowspan='2'>Token</th>       
        <tr>
          <th>Od</th>
          <th>Do</th>
        </tr> 
      </tr>
    </thead>"
    surveys_temp = lecture.surveys.order(start_date: :desc)
	surveys_temp.each do |survey|
		
		html = html + "<tr><td>" + survey.start_date.strftime("%d-%m-%Y")
		html = html + "<td>" + survey.start_date.strftime("%H:%M") 
		html = html + "<td>" + survey.end_date.strftime("%H:%M") 
		html = html + "<td>" + survey.token + "</tr>"
	
	end
	  html = html + "</table>"
	  pdf = WickedPdf.new.pdf_from_string(html, :encoding => "UTF-8") 
	send_data(pdf, 
    :filename    => 'Lista Ankiet '+lecture.name+ '.pdf', 
    :disposition => 'inline'
	) 

  end
  
  # POST /lectures/surveys/1
  # POST /lectures/surveys/1.json
  def index_specific_post
    redirect_to specific_surveys_path(params[:lecture_id])
  end

  # GET /statistics/1
  # GET /statistics/1.json
  def statistics_surveys
    #show statistics for all surveys for specific lecture
      lectures_for_selector = Array.new
      lectures_temp = Lecture.all.order(updated_at: :desc)
      lectures_temp.each do |lecture|
        if lecture.surveys_children? and lecture.number_of_votes > 0
          lectures_for_selector.push([lecture.name, lecture.id])
        end
      end
      flash[:lectures_for_selector] = lectures_for_selector
    @lecture = Lecture.find(params[:id])
    @surveys = @lecture.surveys.order(start_date: :desc)
  end

  # POST /statistics/1
  # POST /statistics/1.json
  def statistics_surveys_post
    redirect_to statistics_surveys_path(params[:lecture_id])
  end

  # GET /statistics/1/1
  # GET /statistics/1.json/1.json
  def statistics_specific
    #graphs for specific lecture/survey combo

    flash.keep
    lecture = Lecture.find(params[:lecture_id_p])
      
      surveys_for_selector = Array.new
      surveys_for_selector.push(['Wszystkie', 0])
      surveys_temp = lecture.surveys.order(start_date: :desc)
      surveys_temp.each do |survey|
        if survey.children? and survey.number_of_votes > 0
          surveys_for_selector.push([survey.start_date.strftime("%d-%m-%Y"), survey.id])
        end
      end
      flash[:surveys_for_selector] = surveys_for_selector
      @survey = lecture.surveys.find(params[:survey_id_p])
      @comments = @survey.scores.where("comment != ?",'')
  end

  # POST /statistics/1/1
  # POST /statistics/1.json/1.json
  def statistics_specific_post
    flash.keep
    if params[:lecture_id_p] != params[:lecture_id]
      redirect_to statistics_surveys_all_path(params[:lecture_id])
    else
      redirect_to statistics_specific_path(params[:lecture_id], params[:survey_id])
    end
  end

  # GET /statistics/1/0
  # GET /statistics/1.json/0.json
  def statistics_surveys_all
    # Graphs for all surveys from select lecture
    flash.keep
    lecture = Lecture.find(params[:lecture_id_p])
      
      surveys_for_selector = Array.new
      surveys_for_selector.push(['Wszystkie', 0])
      surveys_temp = lecture.surveys.order(start_date: :desc)
      surveys_temp.each do |survey|
        if survey.children? and survey.number_of_votes > 0
          surveys_for_selector.push([survey.start_date.strftime("%d-%m-%Y"), survey.id])
        end
      end
      flash[:surveys_for_selector] = surveys_for_selector

      @survey = lecture.surveys.order(start_date: :desc)
  end




  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.all
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
    #UNUSED

  end

  # GET /surveys/new
  def new
    flash.keep
    @survey = Survey.new
  end

  # GET /surveys/1/edit
  def edit
    flash.keep
  end

  # POST /surveys
  # POST /surveys.json
  def create
    #create multiple surveys
    flash.keep
    num_sur = survey_params[:number_of_surveys].to_i
    a=0

    # create number_of_surveys surveys
    for i in 0..num_sur-1
      @survey = Survey.new(survey_params)
      # set correct date
      @survey.start_date=@survey.start_date+(i*@survey.interval.to_i*7).days
      @survey.end_date=@survey.end_date+(i*@survey.interval.to_i*7).days

      # get token from database
      @token=Token.order("RANDOM()").first
      @survey.token=@token.token

      # if save is successful - delete token from databse
      if @survey.save
        a=a+1
        @token.destroy
      else
        break;
      end

    end

    respond_to do |format|
      if a==num_sur and a!=0
        format.html { redirect_to specific_surveys_path(:id => @survey.lecture_id), notice: 'Poprawnie utworzono ankiety.' }
      elsif a>0
        format.html { redirect_to specific_surveys_path(:id => @survey.lecture_id), notice: "Poprawnie utworzono: #{a}  ankiet." }
      else
        format.html { render :new }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1
  # PATCH/PUT /surveys/1.json
  def update
    flash.keep
    if @survey.children? == false
      respond_to do |format|
        if @survey.update(survey_params)
          format.html { redirect_to specific_surveys_path(:id => @survey.lecture_id), notice: 'Poprawnie uaktualniono ankietę.' }
        else
          format.html { render :edit }
          format.json { render json: @survey.errors, status: :unprocessable_entity }
        end
      end
    else
      format.html { redirect_to specific_surveys_path(:id => @survey.lecture_id), notice: 'Na ankietę już głosowano! Nie można jej edytować.' }
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    # if survey has no children (no student voted in the survey) proceed with destroy
    if @survey.children? == false
      @survey.destroy
      respond_to do |format|
        format.html { redirect_to specific_surveys_path(:id => @survey.lecture_id), notice: 'Poprawnie usunięto ankietę.' }
      end
    else
    #if survey has children - do not destroy it and notify the user
      respond_to do |format|
        format.html { redirect_to specific_surveys_path(:id => @survey.lecture_id), notice: 'Na ankietę już głosowano! Nie można jej usunąć.' }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_params
      params.require(:survey).permit(:start_date, :end_date, :interval, :number_of_surveys, :lecture_id)
    end

    def define_layout
    # Check if logged in, because current_user could be nil.
      #if logged_in? and current_user.is_able_to('siteadmin')
        #{}"admin"
      #else
        #{}"application"
      #end
      "user"
    end
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_form.html.erb
<%= form_for @survey, :url => post_surveys_path do |f| %>
  <% if @survey.errors.any? %>
    <div id="error_explanation">
     <h2>Wystąpiła następująca liczba błędów: <%=@survey.errors.count%></h2>

      <ul>
      <% @survey.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class=form>
  <div class="field">
    <%= f.label :"Przedmiot: " %>

    <div>
    <div class="selector_fixed2">
    <div class="styled_select">
    <%= f.select :lecture_id, options_for_select(flash[:lectures_for_selector_s], :selected => flash[:lecture_id_flash]) %>
    </div>
    </div>
    </div>
    <span id="width_tmp"></span>
  </div>

  <div class="field">
	<%= f.label :"Data zajęć: " %>
  <div>
    <div class="start_date">
    <%= f.date_select :start_date %>
    </div>
    <div class="end_date">
    <%= f.date_select :end_date %>
    </div>
  </div>
  </div>
  
    <div class="field">
  <%= f.label :"Ważność tokenu: " %>
   <div> 
    <div class="time_selectors_border">
    <div class="time_field">
      <span>Od:</span>
      <div class="selector_fixed">
      <div class="styled_select">
      <%= select_tag "survey[start_date(4i)]", options_for_select( [["00",0],["01",1],["02",2],["03",3],["04",4],["05",5],["06",6],["07",7],["08",8],["09",9],["10",10],["11",11],["12",12],["13",13],["14",14],["15",15],["16",16],["17",17],["18",18],["19",19],["20",20],["21",21],["22",22],["23",23]], :selected => 12 ) %>
      </div>
      </div>
      <span>:</span>
      <div class="selector_fixed">
      <div class="styled_select">
      <%= select_tag "survey[start_date(5i)]", options_for_select(  [["00",00],["05",05],["10",10],["15",15],["20",20],["25",25],["30",30],["35",35],["40",40],["45",45],["50",50],["55",55]] ) %>
      </div>
      </div>
    </div>
    <div style="display: block;"></div>
    <div class="time_field">
      <span>Do:</span>
      <div class="selector_fixed">
      <div class="styled_select">
      <%= select_tag "survey[end_date(4i)]", options_for_select( [["00",0],["01",1],["02",2],["03",3],["04",4],["05",5],["06",6],["07",7],["08",8],["09",9],["10",10],["11",11],["12",12],["13",13],["14",14],["15",15],["16",16],["17",17],["18",18],["19",19],["20",20],["21",21],["22",22],["23",23]], :selected => 12 ) %>
      </div>
      </div>
      <span>:</span>
      <div class="selector_fixed">
      <div class="styled_select">
      <%= select_tag "survey[end_date(5i)]", options_for_select(  [["00",00],["05",05],["10",10],["15",15],["20",20],["25",25],["30",30],["35",35],["40",40],["45",45],["50",50],["55",55]] ) %>
      </div>
      </div>
    </div>
  </div>
  </div>
  </div>
  

  <div class="field number">
    <%= f.label :"Ankiet: " %>
    <div class="above_zero"><%= f.text_field :number_of_surveys, value:1  %>
    <span class="minus"></span><span class="plus"></span></div>
  </div>
  
  <div class="field">
  <%= f.label :"Co: " %>
    <div class="radio_buttons">
    <div class="radio_holder">
      <%= f.radio_button :interval, '1', :checked => true %>
      <label for="survey_interval_1"></label><br>
      <span>1 tydzień</span>
    </div>
    <div class="radio_holder">
    	<%= f.radio_button :interval, '2' %>
    	<label for="survey_interval_2"></label><br>
      <span>2 tygodnie</span>
    </div>
    <div class="radio_holder">
      <%= f.radio_button :interval, '3' %>
    	<label for="survey_interval_3"></label><br>
      <span>3 tygodnie</span>
    </div>
    </div>
  </div>
  
  <div class="actions hidden">
      <%= f.submit 'Dodaj', :id => 'sumbit_form', :class => 'hidden' %>
  </div>
</div>
<% end %>

app/views/surveys/_form_edit.html.erb
<%= form_for(@survey) do |f| %>
  <% if @survey.errors.any? %>
    <div id="error_explanation">
     <h2>Wystąpiła następująca liczba błędów: <%=@survey.errors.count%></h2>

      <ul>
      <% @survey.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
	<%= f.label :data_zajęć %><br>
    <%= f.date_select :start_date %><br>
    <%= f.time_select :start_date, :ignore_date => true %>
  </div>
  
  <div class="field">
	<%= f.label :HIDDEN_end_date %><br>
    <%= f.date_select :end_date %><br>
    <%= f.time_select :end_date, :ignore_date => true %>
  </div>
  

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/surveys/_form_selector.html .erb
<%= form_tag do %>
 <%= select_tag :lecture_id, options_for_select(Lecture.all.map{|s|[s.name, s.id]}, :selected => params[:id], onchange: "$(this).parent('form').submit();" ) %>
 <%= submit_tag("Go!") %>
<% end %>

app/views/surveys/edit.html.erb
<h1>Editing Survey</h1>

<%= render 'form_edit' %>

<%= link_to 'Back', specific_surveys_path(:id => flash[:lecture_id_flash]) %>

app/views/surveys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Surveys</h1>

<table>
  <thead>
    <tr>
      <th>Token</th>
      <th>Start date</th>
      <th>End date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @surveys.each do |survey| %>
      <tr>
        <td><%= survey.token %></td>
        <td><%= survey.start_date %></td>
        <td><%= survey.end_date %></td>
        <td><%= link_to 'Show', survey %></td>
        <td><%= link_to 'Edit', edit_survey_path(survey) %></td>
        <td><%= link_to 'Destroy', survey, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Survey', new_survey_path %>

app/views/surveys/index_sp.html.erb
<p id="notice"><%= notice %></p>

<h1>Zarządzanie ankietami</h1>

<%= form_tag do %>
 <%= select_tag :lecture_id, options_for_select(Lecture.all.map{|s|[s.name, s.id]}, :selected => params[:id], onchange: "$(this).parent('form').submit();" ) %>
 <%= submit_tag("Go!") %>
<% end %>

<table>
  <thead>  
    <tr>
      <th rowspan="2">Data zajęć</th>
      <th colspan="2">Ważność tokenu</th>
      <th rowspan="2">Token</th>
      <th colspan="2"></th>
      <tr>
        <th>Od</th>
        <th>Do</th>
      </tr> 
    </tr>

  </thead>

  <tbody>
    <% @surveys.each do |survey| %>
      <tr>
        <td><%= survey.start_date.to_date %></td>
        <td><%= survey.start_date.strftime("%H:%M") %></td>
        <td><%= survey.end_date.strftime("%H:%M") %></td>
        <td><%= survey.token %></td>
        <td><%= link_to 'Edytuj', edit_survey_path(survey) %></td>
        <td><%= link_to 'Usuń', survey, method: :delete, data: { confirm: 'Na pewno usunąć?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Generuj nowe', new_survey_path %>

app/views/surveys/index_specific.html.erb
<% content_for :title do %>
  Zarządzanie ankietami
<% end %>

<% content_for :selectors do %>
  <div class="selector left">
    <%= form_tag specific_surveys_path, :id => 'lecture_selector' do %>
      <div class="styled_select">
        <%= select_tag :lecture_id, options_for_select(flash[:lectures_for_selector_s],:selected => params[:id]),onchange: "$('#lecture_selector').submit();"  %>
      </div>
    <% end %>
  </div>
  <span id="width_tmp"></span>
<% end %>


<p id="notice"><%= notice %></p>

<% if @surveys.first != nil %>


  <table>
    <thead>  
      <tr>
        <th rowspan="2"></th>
        <th rowspan="2">Data zajęć</th>
        <th colspan="2">Ważność tokenu</th>
        <th rowspan="2">Token</th>
        <th colspan="2"></th>
        <tr>
          <th>Od</th>
          <th>Do</th>
        </tr> 
      </tr>

    </thead>

    <tbody>
      <% @surveys.each_with_index do |survey,index| %>
        <tr>
          <td class="link"><input type="checkbox" id=<%="checkbox_#{index.to_s}"%> /><label for=<%="checkbox_#{index.to_s}"%>></span></td>
          <td><%= survey.start_date.strftime("%d-%m-%Y") %></td>
          <td><%= survey.start_date.strftime("%H:%M") %></td>
          <td><%= survey.end_date.strftime("%H:%M") %></td>
          <td><%= survey.token %></td>
          <td class="link"><%= 
              if survey.children? == false
                link_to 'Edytuj', edit_survey_path(survey), { :class=>"edit" }
              end 
          %></td>
          <td class="link"><%= 
              if survey.children? == false
                link_to 'Usuń', survey, method: :delete, data: { confirm: 'Na pewno usunąć?' }, class: "delete"
              end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
<% content_for :links do %>

  <%= form_for :lecture, :url => generate_pdf_path do |f| %>
  <%= f.hidden_field :id, :value => params[:id] %>
  <%= f.submit :"Drukuj" , { :class=>"button right" }%>

  <%= link_to 'Generuj nowe', new_survey_path, { :class=>"button right" } %>
  
  

  
<% end %>
  
<% end %>

app/views/surveys/new.html.erb
<% content_for :title do %>
  Nowa ankieta
<% end %>


<%= render 'form' %>

<% content_for :links do %>
	<label for="sumbit_form" class="button right">Generuj</label>
  <%= link_to 'Powrót', specific_surveys_path(:id => flash[:lecture_id_flash]), { :class=>"button right" } %>
<% end %>

app/views/surveys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Token:</strong>
  <%= @survey.token %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @survey.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @survey.end_date %>
</p>

<%= link_to 'Edit', edit_survey_path(@survey) %> |
<%= link_to 'Back', surveys_path %>

app/views/surveys/statistics_surveys.html.erb
<% content_for :title do %>
  Statystyki
<% end %>
<% content_for :selectors do %>
  <div class="selector left">
    <%= form_tag statistics_surveys_path, :id => 'lecture_selector' do %>
      <div class="styled_select">
        <%= select_tag :lecture_id, options_for_select(flash[:lectures_for_selector],:selected => params[:id]),onchange: "$('#lecture_selector').submit();"  %>
      </div>
<% end %>
  </div>
  <span id="width_tmp"></span>
<% end %>

<p id="notice"><%= notice %></p>

<table>
  <thead>  
    <tr>
      <th>Data zajęć</th>
      <th>Wrażenie ogólne</th>
      <th>Tempo</th>
      <th>Pożyteczność wiedzy</th>
      <th>Komentarzy</th>
      <th>Głosów</th>
    </tr>
  </thead>

  <tbody>
    <% @surveys.each do |survey| %>
      <tr>
        <td><%= survey.start_date.strftime("%d-%m-%Y") %></td>
        <td><%= survey.average_general_score.to_f.round(2) %></td>
        <td><%= survey.average_tempo_score.to_f.round(2) %></td>
        <td><%= survey.average_importance_score.to_f.round(2) %></td>
        <td><%= survey.number_of_comments %></td>
        <td><%= survey.number_of_votes %></td>
        <td class="link"><%= 
          if survey.number_of_votes > 0
            link_to '=>', statistics_specific_path(:lecture_id_p => params[:id], :survey_id_p => survey.id), { :class=>"goto" }
          end
        %></td>
      </tr>
    <% end %>
      <tr class="summary_row">
        <td>Ogółem</td>
        <td><%= @lecture.average_general_score %></td>
        <td><%= @lecture.average_tempo_score %></td>
        <td><%= @lecture.average_importance_score %></td>
        <td><%= @surveys.map{|item| item.number_of_comments}.reduce(0, :+) %></td>
        <td><%= @lecture.number_of_votes %></td>
        <td class="link"><%=
          if @lecture.number_of_votes > 0
            link_to '=>', statistics_surveys_all_path(:lecture_id_p => params[:id]), { :class=>"goto" }
          end 
        %></td>
      </tr>
  </tbody>
</table>

<% content_for :links do %>
  <%= link_to 'Powrót', statistics_path, { :class=>"button right" } %>
<% end %>

app/views/surveys/statistics_surveys_all.html.erb
<% content_for :title do %>
Statystyki
<% end %>

<% content_for :selectors do %>
	<%= form_tag statistics_surveys_all_path, :id => 'lecture_selector' do %>
	 <div class="selector left">
		 <div class="styled_select">
	 		<%= select_tag :lecture_id, options_for_select(flash[:lectures_for_selector],:selected => params[:lecture_id_p]),onchange: "$('#lecture_selector').submit();"  %>
	 	 </div>
	 </div>
	 <div class="selector2 right">
		 <div class="styled_select">
	 		<%= select_tag :survey_id, options_for_select(flash[:surveys_for_selector],:selected => 0),onchange: "$('#lecture_selector').submit();"  %>
	 	 </div>
	 </div>
	<% end %>
	<span id="width_tmp"></span>
<% end %>

<p id="notice"><%= notice %></p>

<p id = "number_of_votes">
  Głosów:
<%= @survey.first.lecture.number_of_votes %>
</p>
<p id = "general_score">
<%= @survey.first.lecture.average_general_score %>
</p>
<p id = "tempo_score">
<%= @survey.first.lecture.average_tempo_score %>
</p>
<p id = "importance_score">
<%= @survey.first.lecture.average_importance_score %>
</p>
<p id = "comments">
Komentarze
<%= @survey.map{|item| item.number_of_comments}.reduce(0, :+) %>
</p>

<% content_for :links do %>
  <%= link_to 'Powrót', statistics_surveys_path(:id => params[:lecture_id_p]), { :class=>"button right" } %>
<% end %>