config/routes.rb
Rails.application.routes.draw do

  get 'log_in' => 'sessions#new', :as => 'log_in'
  get 'log_out' => 'sessions#destroy', :as => 'log_out'
  get 'sign_up' => 'students#new', :as => 'sign_up'

 resources :surveys
  post 'scores/new', to:'scores#new_post', as:'new_score_post'
  get 'scores/new', to:'scores#index', as:'new_score_get'
  resources :scores

  resources :surveys

  match 'surveys/new', :to => 'surveys#create', 
                       :via => :post, 
                       :as => :post_surveys
					   
    post '/pdf', to:'surveys#generate_pdf', as: 'generate_pdf' 
	get '/pdf', to:'lectures#index', as:'generate_pdf_get'

  get '/lectures/surveys/:id', to:'surveys#index_specific', as:'specific_surveys'
  
  post '/lectures/surveys/:id', to:'surveys#index_specific_post'

  resources :students
  resources :sessions

  get '/lectures', to:'lectures#index', as:'all_lectures'
  patch '/lectures/:id', to:'lectures#update'
  put '/lectures/:id', to:'lectures#update'
  delete '/lectures/:id', to:'lectures#destroy', as:'delete_lecture'
  resource :lectures
  get '/lectures/:id', to:'lectures#show', as:'lecture'
  get '/lectures/edit/:id', to:'lectures#edit', as:'edit_lecture'

  get '/statistics', to:'lectures#statistics', as:'statistics'
  get '/statistics/:id', to:'surveys#statistics_surveys', as:'statistics_surveys'
  post '/statistics/:id', to:'surveys#statistics_surveys_post'
  get '/statistics/:lecture_id_p/0', to:'surveys#statistics_surveys_all', as:'statistics_surveys_all'
  post '/statistics/:lecture_id_p/0', to:'surveys#statistics_specific_post'
  get '/statistics/:lecture_id_p/:survey_id_p', to:'surveys#statistics_specific', as:'statistics_specific'
  post '/statistics/:lecture_id_p/:survey_id_p', to:'surveys#statistics_specific_post'

   root 'welcome#index'

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>eAnkieta</title>
  <meta name="viewport" content="width=device-width" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

     
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/user.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myapp</title>
  <%= stylesheet_link_tag    "user", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="limiter">
	<div id="nav">
  		<%= render_navigation %>
	</div>
	
	<!--
	<div id="user_nav">
		<% if current_user %>
		Zalogowano jako <%= current_user.index %>
			<%= link_to "Wyloguj się", log_out_path %>
		<% else %>
			<%= link_to "Zarejestruj się", sign_up_path %> lub 
			<%= link_to "zaloguj się", log_in_path %>
		<% end %>
	</div>
	-->
	<div class="content">
  		<div class="container">
    		<div class="title">
      			<h2><%= yield :title %></h2>
    		</div>

    		<div class="inner_content">
    			<%= yield :selectors %>
    			<div class="data">
    				<%= yield %>
    			</div>
    		</div>
    		<div class="footer">
   				<%= yield :links %>
      		</div>
    	</div>
    </div>
</div>
</body>
</html>